config/routes.rb
Rails.application.routes.draw do

 root 'static_pages#index'

  get 'about'     =>  'static_pages#about'

  get 'design'    =>  'static_pages#design'

  get 'project'   =>  'static_pages#project'

  get 'contact'   =>  'static_pages#contact'

  get 'complete'  =>  'static_pages#complete'

  get 'progress'  =>  'static_pages#progress'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def design
  end

  def projects
  end

  def contacts
  end

  def complete
    
  end

  def progress
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_carouselslider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <%= image_tag("bb3.jpg", :alt => "architectural Designing", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>description</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag("bb1.jpg", :alt => "School moto", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>description</p>
        </div>
      </div>
    
      <div class="item">
        <%= image_tag("bb2.jpg", :alt => "School m", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>Description</p>
        </div>
      </div>

  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pax english medium school © 2016
  </small>
  <nav>
    <ul>
      <li><a href="http://www.maitco.co.tz" target="blank">Designer</a></li>
      <li> | </li>
      <li><%= link_to "Location and Direction", '#' %></li>
    </ul>
    <div class="fb-like" data-href="https://facebook.com/maitco" data-layout="standard" data-action="like"       data-show-faces="true" data-share="true">
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Designing", design_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Projects", project_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Contacts", contact_path %></li>
      
      </ul>

      <div class="social-icon">
         <a href="http://twitter.com/minimalmonkey" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
        <a href="http://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
        <a href="http://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  	<ul class="notice">
  	  <h4>Notice board</h4>
  		<li>Parent meeting.</li>
  		<li>School board meeting</li>
  		<li>First sermister examination</li>
  		<li>Changes in school timetable</li>
  	</ul>
  	<ul class="downloads">
  		<h4>Quick downloads link</h4>
  		<li>Admission form 2016</li>
  		<li>Fee structure</li>
  		<li>School rules</li>
  	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Build Beast</title>
  <link rel="stylesheet" type="text/css" href="http://www.w3schools.com/lib/w3.css">
  <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
  <%= csrf_meta_tags %>
 
</head>
<body>
  <div class="container">
   <img>
    <%= image_tag("banner.png", :alt => "logo", :class=>"banner") %>
   </img>
   
   <%= render 'layouts/header' %>

   <%= yield %>

  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<div id="content">

	<div id="sider-left">
		<head class="description">
			<h2>About Us</h2>
			<p>BuilBeast is a full service design/build contractor located in Dar es salaam, Tanzania. </p>
			<h3>(+255) 789 291 159</h3>
			<p>Email: <em>buildbeast@gmail.com</em></p>
			<p>Some street, block no #<br/> 1st floor<br/>Dar es salaam</p>
			<hr/>
		</head>
		<add class="advertise">
			<h1> Addon goes here</h1>
		</add>
	</div>
	<div id="sider-right">
		<div class="container1">
			<h2>Who Are We?</h2>
			<p>BuildBeast's success is a result of our ability to satisfy the needs and goals of our clients for over many(#) years. We are not so much in the business of securing projects as we are in the business of satisfying clients. We accomplish this with professionalism, honesty, creativity, and most importantly, performance.</p>

			<p>BuildBeast offers single - source convenience. Once you have identified a building need, we are prepared to work with you all the way from concept to occupancy.</p>

			<p>The Design/Build process enables BuildBeast Building and Engineering Co., Inc. to represent its customers during all stages of a project, including planning, in- house design, obtaining approvals and permits, cost analysis, and construction. The Design/Build approach provides the benefits of substantially reducing the construction timetable; saving the client time and money. Through experience, we know which building products will provide economy at the performance level needed. We balance price and value to achieve the best cost/quality solution.</p>

			<p>BuildBeast's strongest asset is its people. We are a dedicated team of knowledgeable, experienced, hard working people who are committed to maintaining top performance and satisfying its clients.</p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div id="content">

	<div id="sider-left">
		<head class="description">
			<h2>We would like to discus your project with you.</h2>
			<p>P.o.box 11111 <br/>Dar es salaam-Tanzania</p>
			<h3>(+255) 789 291 159</h3>
			<p>Email: <em>buildbeast@gmail.com</em></p>
			<p>Some street, block no #<br/> 1st floor<br/>Dar es salaam</p>
			<hr/>
		</head>
		<add class="advertise">
			<h1> Addon goes here</h1>
		</add>
	</div>
	<div id="sider-right">
		<div class="container1">
			<h3>Send us a message</h3>
			<form action="#" class="form">
				Required field*
				Name*:<br> <input type="text" name="name" class="field" size=""></input><br>
				Email*:<br> <input type="email" name="email" class="field" size=""></input><br>
				Phone: <br> <input type="text" name="number" class="field" size=""></input><br>
				Comments / Questions /Feedback:<br> <textarea name="coment" ></textarea><br> 
				<input type="submit"></input>
			</form>
		</div>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d995.7277513255874!2d36.685659488080184!3d-3.3719286610626518!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zM8KwMjInMTguOSJTIDM2wrA0MScxMC4zIkU!5e0!3m2!1sen!2stz!4v1459076051845" width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/static_pages/design.html.erb
<div id="content">

	<div id="sider-left">
		<head class="description">
			<h2>Professional Designing</h2>
			<p>BuilBeast is a full service design/build contractor located in Dar es salaam, Tanzania. </p>
			<h3>(+255) 789 291 159</h3>
			<p>Email: <em>buildbeast@gmail.com</em></p>
			<p>Some street, block no #<br/> 1st floor<br/>Dar es salaam</p>
			<hr/>
		</head>
		<add class="advertise">
			<h1> Addon goes here</h1>
		</add>
	</div>
	<div id="sider-right">
		<div class="container1">
			<p>BuildBeast provides excellent professional in-house engineering and design services. We apply these standards to every project, using a combination of framing styles and building sizes and materials to fit your building needs.</p>
			<p>BuildBeast designs each building to:</p>
			<ul class="design">
				<li>Look distinctive and different from other buildings</li>
				<li>Accommodate the specific business needs of the client</li>
				<li>Stand the test of time with low maintenance</li>
			</ul>
			<p>BuildBeast provides:</p>
			<ul>
				<li>Preliminary cost estimates for planing</li>
				<li>Final cost estimates for building construction</li>
				<li>Pre-engineered structural, wall and roofing system that can save you energy, time and money. This state-of-the art technology, along with our fast-track Design/Build construction expertise, is the best solution.</li>
			</ul>
		</div>
	</div>
</div>

app/views/static_pages/index.html.erb
<div id="content">

	<div id="sider-left">
		<head class="description">
			<h2>Building Ideas, That Works For You</h2>
			<p>BuilBeast is a full service design/build contractor located in Dar es salaam, Tanzania. </p>
			<h3>(+255) 789 291 159</h3>
			<p>Email: <em>buildbeast@gmail.com</em></p>
			<p>Some street, block no #<br/> 1st floor<br/>Dar es salaam</p>
			<hr/>
		</head>
		<add class="advertise">
			<h1> Addon for the company or related membership company</h1>
		</add>
	</div>
	<div id="sider-right">
		<%= render 'layouts/carouselslider' %>
		<div class="container1">
			<h2>Welcome to BuildBeast</h2>
			<p>BuildBeast Building and Engineering Co., Inc. provides quality buildings, excellent service and offers single - source responsibility for building services. BuildBeast specializes in commercial, industrial and retail/office facilities. <em>"Building Ideas That Work"</em> is our motto and guides our direction. We offer complete "in-house" design, planning and construction services. The Design/ Build concept is fundamental to our business. Our experienced staff works in partnership with our clients at every stage of development, from the preparation of a preliminary budget to the design and construction of the project.</p>

			<p>BuildBeast's approach of using the Design/Build process provides our customers with the optimum design to fit within their budget from a cost, appearance, and performance standpoint. We use a variety of conventional and pre-engineered construction techniques selecting masonry, concrete wall panels, glass wall systems, etc. and Butler pre-engineered building systems in a skillful combination.</p>

			<p>Complete construction is our business - from concept, to drawings, to completion.</p>

			<p>BuildBeast Building and Engineering Co., Inc. - "Building Ideas That Work" can work for you.</p>
		</div>
	</div>
</div>

app/views/static_pages/project.html.erb
<div id="content">

	<div id="sider-left">
		<head class="description">
			<h2>Our project</h2>
			<ul>
				<li><%= link_to "Complete", complete_path %></li>
				<li><%= link_to "In progress", progress_path %></li>
			</ul>
			<hr/>
		</head>
		<add class="advertise">
			<h1> Addon goes here</h1>
		</add>
	</div>
	<div id="sider-right">
	  <h3>Complete Projects</h3>
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
  		</div>
	
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
		</div>
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
		</div>
	</div>
	<div id="sider-right">
		<h3>In-progress Projects</h3>
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
  		</div>
	
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
		</div>
		<div class="img">
  			<a target="_blank" href="#">
  			  <%= image_tag("bb_logo.png", :alt => "project1") %>
  			</a>
  			<div class="desc">Add a description of the image here</div>
		</div>
	</div>
</div>